Resources:
  AuditPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: cost-opt-audit-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyReadAccessToObjectsStoringCustomerData
            Effect: Deny
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:Query
              - dynamodb:Scan
              - ec2messages:GetMessages
              - ecr:BatchCheckLayerAvailability
              - ecr:GetAuthorizationToken
              - ecr:GetDownloadUrlForLayer
              - kinesis:GetRecords
              - kinesis:SubscribeToShard
              - logs:GetLogEvents
              - logs:GetLogRecord
              - neptune-db:GetStreamRecords
              - neptune-db:ReadDataViaQuery
              - s3:GetObject
              - secretsmanager:BatchGetSecretValue
              - secretsmanager:GetSecretValue
              - sqs:ReceiveMessage
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - ssm:StartSession # remote access to EC2 instance
              - timestream:Select
              - timestream:SelectValues
            Resource: "*"

          - Sid: DenyAnyModificationsAroundCosts
            Effect: Deny
            Action:
              - aws-portal:Modify*
              - budgets:ModifyBudget
              - ce:CreateNotificationSubscription
              - ce:CreateReport
              - ce:DeleteNotificationSubscription
              - ce:DeleteReport
              - ce:UpdateNotificationSubscription
              - ce:UpdatePreferences
              - ce:UpdateReport
              - cur:DeleteReportDefinition
              - cur:ModifyReportDefinition
              - cur:PutReportDefinition
              - purchase-orders:Delete*
              - purchase-orders:Modify*
              - purchase-orders:Update*
            Resource: "*"

          - Effect: Allow
            Action:
              - apigateway:Get*
              - application-autoscaling:DescribeScalableTargets
              - aws-portal:View*
              - batch:Describe*
              - batch:List*
              - billing:ListBillingViews
              - ce:Describe*
              - ce:Get*
              - ce:List*
              - cloudfront:Get*
              - cloudfront:ListDistributions
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListDashboards
              - cloudwatch:ListMetrics
              - cloudwatch:ListMetricStreams
              - cloudwatch:ListTagsForResource
              - compute-optimizer:*EnrollmentStatus
              - cur:DescribeReportDefinitions
              - dynamodb:DescribeTable
              - dynamodb:ListTables
              - ebs:ListChangedBlocks
              - ebs:ListSnapshotBlocks
              - ec2:Describe*
              - ec2:DescribeSnapshots
              - ec2:DescribeSnapshotTierStatus
              - ecr:DescribeImages
              - ecr:DescribeRegistry
              - ecr:DescribeRepositories
              - ecr:ListImages
              - eks:AccessKubernetesApi
              - elasticfilesystem:DescribeAccessPoints
              - elasticloadbalancing:DescribeInstanceHealth
              - elasticloadbalancing:DescribeListeners
              - elasticloadbalancing:DescribeLoadBalancerAttributes
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeTargetHealth
              - iam:GetAccountSummary
              - iam:GetPolicy
              - iam:ListAccountAliases
              - logs:DescribeLogGroups
              - organizations:ListAccounts
              - pi:GetResourceMetrics
              - pricing:DescribeServices
              - pricing:GetAttributeValues
              - pricing:GetProducts
              - purchase-orders:ViewPurchaseOrders
              - rds:DescribeDBClusters
              - rds:DescribeDBInstances
              - s3:GetAccessPoint
              - s3:GetBucketLocation
              - s3:GetBucketLogging
              - s3:GetBucketPolicy
              - s3:GetBucketPolicyStatus
              - s3:GetBucketTagging
              - s3:GetBucketVersioning
              - s3:GetEncryptionConfiguration
              - s3:GetIntelligentTieringConfiguration
              - s3:GetInventoryConfiguration
              - s3:GetLifecycleConfiguration
              - s3:GetMetricsConfiguration
              - s3:GetReplicationConfiguration
              - s3:GetStorageLens*
              - s3:GetStorageLensConfiguration
              - s3:GetStorageLensDashboard
              - s3:ListAllMyBuckets
              - s3:ListBucketMultipartUploads
              - s3:ListBucketVersions
              - s3:ListMultipartUploadParts
              - s3:ListMultiRegionAccessPoints
              - s3:ListStorageLens*
              - s3:ListStorageLensConfigurations
              - secretsmanager:ListSecrets
              - secretsmanager:ListSecrets
              - servicediscovery:List*
              - trustedadvisor:RefreshCheck
            Resource: "*"

          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: arn:aws:iam::*:role/aws-service-role/compute-optimizer.amazonaws.com/AWSServiceRoleForComputeOptimizer*
            Condition:
              StringLike:
                iam:AWSServiceName: compute-optimizer.amazonaws.com

          - Effect: Allow
            Action: iam:PutRolePolicy
            Resource: arn:aws:iam::*:role/aws-service-role/compute-optimizer.amazonaws.com/AWSServiceRoleForComputeOptimizer

  AuditRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cost-opt-audit-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::658620001254:user/paweliq
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref AuditPolicy
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSSavingsPlansReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudSearchReadOnlyAccess
        - arn:aws:iam::aws:policy/ComputeOptimizerReadOnlyAccess
        - arn:aws:iam::aws:policy/job-function/Billing
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  EventBridgeRuleNotifyUponCreation:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "cost-opt-audit-notify-on-creation"
      EventPattern:
        source:
          - "aws.cloudformation"
        detail-type: 
          - "CloudFormation Stack Status Change"
        detail:
          stack-id: 
            - wildcard: !Sub "arn:aws:cloudformation:*:*:stack/${AWS::StackName}*"
          status-details:
            status:
              - "CREATE_COMPLETE"
      State: "ENABLED"
      Targets:
        - Arn: "arn:aws:events:eu-central-1:658620001254:event-bus/cost-audit-client-account-enrolled"
          Id: "TargetEventBus"
          RoleArn: !GetAtt EventBusCrossAccountRole.Arn
          DeadLetterConfig:
            Arn: !GetAtt  EventBridgeRuleDlq.Arn

  EventBridgeRuleDlq:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: cost-opt-audit-notify-dlq
  
  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sqs:SendMessage
          Resource: !GetAtt EventBridgeRuleDlq.Arn
      Queues:
        - Ref: EventBridgeRuleDlq

  EventBusCrossAccountRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EventBusCrossAccountRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole

  EventBusCrossAccountPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "EventBusCrossAccountPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "CrossAccountPublish"
            Effect: "Allow"
            Action: "events:PutEvents"
            Resource: "arn:aws:events:eu-central-1:658620001254:event-bus/cost-audit-client-account-enrolled"
      Roles:
        - Ref: "EventBusCrossAccountRole"